"""Strict, auditable workforce-planning model for the Beeline case."""

from .domain import (
    Commitment,
    Engineer,
    Equipment,
    EquipmentNeed,
    Event,
    Job,
    Office,
    PlanningDataset,
    Priority,
    RequiredTransport,
)
from .counterfactual import (
    CounterfactualResult,
    CounterfactualStatus,
    counterfactual_result_dict,
    evaluate_event_assignment_counterfactual,
    evaluate_initial_assignment_counterfactual,
)
from .eligibility import CandidateIndex, RejectionCode, build_candidate_index
from .explanations import ClaimLevel, build_explanation_bundle
from .errors import HardModelInfeasible, InvalidPlanningData, PlanningError
from .loader import load_planning_dataset
from .master import MasterArc, MasterModelInput, build_master_model_input
from .materialize import (
    MaterializationFailure,
    MaterializationResult,
    MaterializationStatus,
    materialize_exact_initial_plan,
)
from .plan import EngineerPlan, IdentityTravel, PlannedVisit, ProposedPlan
from .quality import ScreeningSolutionQuality, screening_solution_quality
from .refinement import (
    ExactArcObservation,
    ExactRefinementFailure,
    ExactRefinementReport,
    ExactRouteProbeFailure,
    ExactRouteProbeReport,
    ProbeFailureKind,
    RefinementFailureKind,
    RefinementActions,
    apply_refinement_report,
    inspect_exact_candidate,
    probe_exact_initial_plan_routes,
)
from .replanning import (
    CandidateEvaluation,
    ReplanningResult,
    ReplanningState,
    ReplanningStatus,
    replan_after_event,
)
from .screening import (
    ScreeningCell,
    ScreeningEstimate,
    ScreeningMatrices,
    load_screening_matrices,
)
from .solver import (
    MasterEngineerRoute,
    MasterSolution,
    MasterSolveStatus,
    MasterVisit,
    ObjectivePolicy,
    ObjectiveProof,
    SolverConfig,
    solve_screening_master,
)
from .team_compaction import (
    RouteEvaluation,
    TeamEliminationCandidate,
    TeamEliminationSearchReport,
    build_screening_route_evaluator,
    find_team_elimination_candidates,
)
from .validator import (
    PlanMetrics,
    ValidationReport,
    ValidationStatus,
    Violation,
    ViolationCode,
    validate_initial_plan,
    validate_replanned_plan,
)

__all__ = [
    'CandidateIndex',
    'CandidateEvaluation',
    'ClaimLevel',
    'Commitment',
    'CounterfactualResult',
    'CounterfactualStatus',
    'Engineer',
    'Equipment',
    'EquipmentNeed',
    'EngineerPlan',
    'ExactArcObservation',
    'ExactRefinementFailure',
    'ExactRefinementReport',
    'ExactRouteProbeFailure',
    'ExactRouteProbeReport',
    'Event',
    'HardModelInfeasible',
    'InvalidPlanningData',
    'IdentityTravel',
    'Job',
    'MasterArc',
    'MasterEngineerRoute',
    'MasterModelInput',
    'MasterSolution',
    'MasterSolveStatus',
    'MasterVisit',
    'MaterializationFailure',
    'MaterializationResult',
    'MaterializationStatus',
    'Office',
    'ObjectivePolicy',
    'ObjectiveProof',
    'PlanningDataset',
    'PlanningError',
    'PlannedVisit',
    'PlanMetrics',
    'Priority',
    'ProbeFailureKind',
    'RefinementFailureKind',
    'RefinementActions',
    'ProposedPlan',
    'RejectionCode',
    'ReplanningResult',
    'ReplanningState',
    'ReplanningStatus',
    'RequiredTransport',
    'RouteEvaluation',
    'ScreeningCell',
    'ScreeningEstimate',
    'ScreeningMatrices',
    'ScreeningSolutionQuality',
    'SolverConfig',
    'TeamEliminationCandidate',
    'TeamEliminationSearchReport',
    'ValidationReport',
    'ValidationStatus',
    'Violation',
    'ViolationCode',
    'build_candidate_index',
    'apply_refinement_report',
    'build_explanation_bundle',
    'build_master_model_input',
    'build_screening_route_evaluator',
    'load_planning_dataset',
    'load_screening_matrices',
    'materialize_exact_initial_plan',
    'counterfactual_result_dict',
    'evaluate_event_assignment_counterfactual',
    'evaluate_initial_assignment_counterfactual',
    'inspect_exact_candidate',
    'probe_exact_initial_plan_routes',
    'replan_after_event',
    'solve_screening_master',
    'find_team_elimination_candidates',
    'screening_solution_quality',
    'validate_initial_plan',
    'validate_replanned_plan',
]
