server {
    listen 80;
    server_name 84.252.135.110;
    root /opt/beego/current/site/dist/client;
    index index.html;
    client_max_body_size 20m;
    gzip on;
    gzip_min_length 1024;
    gzip_types application/json text/css application/javascript;

    location /api/ {
        proxy_pass http://127.0.0.1:8787;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_read_timeout 930s;
        proxy_send_timeout 930s;
    }

    location /assets/ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
